version: '3'

services:
  redis_server:
    image: redis
    container_name: redis_server_db
    command: redis-server --requirepass ${REDIS_PASSWORD}    
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: